#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    systemd-sysusers /usr/lib/sysusers.d/ios-safari-debug-stack.conf
fi

#DEBHELPER#

if [ "$1" = "configure" ] && [ -z "${2:-}" ] && [ -d /run/systemd/system ]; then
    systemctl daemon-reload || true
    systemctl enable ios-safari-debug-wip.service ios-safari-debug-ui.service || true
    systemctl start ios-safari-debug-wip.service ios-safari-debug-ui.service || true
fi

exit 0
